#!/bin/bash

# make sure we have lpass installed
export PATH
LPASS="$(which lpass)" || { echo "Please have the lpass binary in your path" && exit 1; }
# depending on the OS HOME is going to be different
[[ "`uname`" == "Linux" ]] && USER_HOME="/home/dsteen"
[[ "`uname`" == "Darwin" ]] && USER_HOME="/Users/dsteen"

# get our variables
SOURCE_DIR="$1"
MOUNT_DIR="$2"
# get the password depending on what mount we are doing
case "$MOUNT_DIR" in
  /home/dsteen/documents/documents)
    PASS="$(HOME="${USER_HOME}" ${LPASS} show 'cryptomator documents' -j |jq -r '.[].password')"
    ;;
  /home/dsteen/documents/traitify_documents)
    PASS="$(HOME="${USER_HOME}" ${LPASS} show 'cryptomator traitify documents' -j |jq -r '.[].password')"
    ;;
  *)
    # default to our secrets dir
    SOURCE_DIR="${USER_HOME}/Dropbox/Dan Files/secure"
    MOUNT_DIR="${USER_HOME}/secure"
    PASS="$(HOME="${USER_HOME}" ${LPASS} show secure.img --notes)"
    ;;
esac


# old dm-crypt method
#echo -n "$PASS" | sudo cryptsetup luksOpen --key-file - secure.img dsteen_secure
#sudo mount /dev/mapper/dsteen_secure /home/dsteen/secure
#sudo mount -o bind /home/dsteen/secure/.ssh /home/dsteen/.ssh

# new encfs method
# put the following in fstab:
#<path to this script>#/home/dsteen/Dropbox/Dan\040Files/secure /home/dsteen/secure  fuse  noauto,user  0  0
# or we can allow this to run manually
#[ -z "$*" ] && PARAMS="/home/dsteen/Dropbox/Dan\ Files/secure /home/dsteen/secure"
# wsl needs us to set the permissions on /dev/fuse
[[ "`uname -r`" == *"microsoft"* ]] && sudo /bin/chmod g+rw /dev/fuse && sudo /bin/chgrp fuse /dev/fuse
echo -n "$PASS" | encfs -S "$SOURCE_DIR" "$MOUNT_DIR"

# cryptomator method
#bindfs -p 700 --create-as-user --no-allow-other -o nonempty ~/secure/.ssh ~/.ssh

